apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: datastore
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
        - image: cheapacr.azurecr.io/datastore:3d67cb0f612d2bb2d734988bf2fe8aaf61f78d8e
          name: datastore
          ports:
            - containerPort: 3000
          env:
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/opt/firebase/creds.json"
      volumeMounts:
        - name: secret-volume # matches secret name
          mountPath: "/opt/firebase"
          readOnly: true # no editing!
    volumes:
      # create volumes
      - name: secret-volume # name to match for mounting
        secret:
          secretName: firebase-secret # name of secret
