apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: datastore
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
        - image: cheapacr.azurecr.io/datastore:3d67cb0f612d2bb2d734988bf2fe8aaf61f78d8e
          name: datastore
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: datastore-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
